inventory: move serial console from manager to system
SerialConsole was deprecated in Manager v1_10_0 and has been
removed in bmcweb [1].

Because the SerialConsole values were not available anymore, the
Managers were not displayed because "setBmcInfo" couldn't find the
"SerialConsole" properties. In the browser it failed with:

 TypeError: Cannot read properties of undefined (reading 'ConnectTypesSupported')
     at Wa.setBmcInfo (app.25e72670.js:58:745295)
     at app.25e72670.js:50:2774
     at app.25e72670.js:50:10113
     at Array.forEach (<anonymous>)
     at app.25e72670.js:50:10092
     at Wa._withCommit (app.25e72670.js:50:11953)
     at Wa.commit (app.25e72670.js:50:10066)
     at Wa.commit (app.25e72670.js:50:9518)
     at o.commit (app.25e72670.js:50:2216)
     at app.25e72670.js:58:745747

[1]: https://github.com/openbmc/bmcweb/commit/fa800c8a141aa4b209269e0fb50cae34aa24f75d

Tested: BMC manager being listed in the inventory and serial console
        variables being displayed for the system.

Change-Id: I1a24178717805ca50eef2c89042c0bd9ede1d5bc
Signed-off-by: Tan Siewert <tan@siewert.io>